/**
 * Bundled template files for the create-bgio-partykit CLI.
 *
 * Template variables use the `{{VARIABLE}}` syntax and are replaced
 * at scaffold time with user-provided values:
 *   - {{PROJECT_NAME}}      — kebab-case project directory name
 *   - {{GAME_NAME}}         — boardgame.io game name (defaults to project name)
 *   - {{GAME_NAME_PASCAL}}  — PascalCase version of game name (for TypeScript identifiers)
 *   - {{NUM_PLAYERS}}       — number of players (default 2)
 *   - {{BGIO_PK_VERSION}}   — bgio-partykit dependency version
 */

export interface TemplateVars {
  projectName: string;
  gameName: string;
  numPlayers: number;
  bgioPkVersion: string;
}

function toPascalCase(kebab: string): string {
  return kebab
    .split(/[-_]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function substitute(template: string, vars: TemplateVars): string {
  const gameNamePascal = toPascalCase(vars.gameName);
  return template
    .replace(/\{\{PROJECT_NAME\}\}/g, vars.projectName)
    .replace(/\{\{GAME_NAME\}\}/g, vars.gameName)
    .replace(/\{\{GAME_NAME_PASCAL\}\}/g, gameNamePascal)
    .replace(/\{\{NUM_PLAYERS\}\}/g, String(vars.numPlayers))
    .replace(/\{\{BGIO_PK_VERSION\}\}/g, vars.bgioPkVersion);
}

export interface TemplateFile {
  path: string;
  content: (vars: TemplateVars) => string;
}

const rawTemplates: Array<{ path: string; content: string }> = [
  // ─── package.json ────────────────────────────────────────────
  {
    path: "package.json",
    content: `{
  "name": "{{PROJECT_NAME}}",
  "version": "1.0.0",
  "private": true,
  "description": "My boardgame.io game on PartyKit",
  "type": "module",
  "scripts": {
    "dev": "partykit dev --port 1999",
    "build": "tsc --noEmit",
    "typecheck": "tsc --noEmit",
    "deploy": "partykit deploy"
  },
  "dependencies": {
    "bgio-partykit": "{{BGIO_PK_VERSION}}",
    "boardgame.io": "^0.50.0"
  },
  "devDependencies": {
    "typescript": "^5.8.3",
    "partykit": "^0.0.115",
    "@types/node": "^22.15.0"
  },
  "engines": {
    "node": ">=20"
  },
  "pnpm": {
    "onlyBuiltDependencies": ["esbuild", "workerd"],
    "patchedDependencies": {
      "capnp-ts@0.7.0": "patches/capnp-ts@0.7.0.patch"
    }
  }
}
`,
  },

  // ─── partykit.json ───────────────────────────────────────────
  {
    path: "partykit.json",
    content: `{
  "name": "{{PROJECT_NAME}}",
  "main": "src/server.ts",
  "compatibilityDate": "2024-07-01",
  "parties": {
    "lobby": "src/server.ts",
    "match": "src/server.ts"
  }
}
`,
  },

  // ─── tsconfig.json ───────────────────────────────────────────
  {
    path: "tsconfig.json",
    content: `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022"],
    "types": ["node"],
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "outDir": "dist",
    "rootDir": "."
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist", ".partykit"]
}
`,
  },

  // ─── src/server.ts (PartyKit room entrypoint) ─────────────────
  {
    path: "src/server.ts",
    content: `/**
 * PartyKit server entrypoint for {{PROJECT_NAME}}.
 *
 * This file was generated by create-bgio-partykit.
 * It demonstrates how to use the bgio-partykit package to:
 * 1. Register your game using the public API
 * 2. Export the PartyKit Server class as the default export
 */

import { Server, registerGame } from "bgio-partykit";
import { {{GAME_NAME_PASCAL}} } from "./game.js";

// Register the game before the server starts handling requests
registerGame({{GAME_NAME_PASCAL}});

// Export the Server class as the PartyKit entrypoint
export default Server;
`,
  },

  // ─── src/game.ts (Starter game definition) ───────────────────
  {
    path: "src/game.ts",
    content: `/**
 * A starter boardgame.io game definition for {{PROJECT_NAME}}.
 *
 * This is a simple turn-taking game where players take turns
 * making a single move each turn. Customize the moves, setup,
 * and endIf to build your own game.
 */

import type { Game } from "boardgame.io";

export interface {{GAME_NAME_PASCAL}}State {
  /** Example field: counts moves made across all players */
  moveCount: number;
  /** Per-player scores */
  scores: Record<string, number>;
}

export const {{GAME_NAME_PASCAL}}: Game<{{GAME_NAME_PASCAL}}State> = {
  name: "{{GAME_NAME}}",
  minPlayers: {{NUM_PLAYERS}},
  maxPlayers: {{NUM_PLAYERS}},

  setup: ({ ctx }) => ({
    moveCount: 0,
    scores: Object.fromEntries(
      ctx.playOrder.map((id) => [id, 0]),
    ),
  }),

  turn: {
    maxMoves: 1,
  },

  moves: {
    /** Example move: increment the current player's score */
    takeTurn: ({ G, ctx }) => {
      G.scores[ctx.currentPlayer]++;
      G.moveCount++;
    },
  },

  endIf: ({ G, ctx }) => {
    // End after 10 total moves (5 rounds for a 2-player game)
    if (G.moveCount >= 10) {
      let winner: string | undefined;
      let highScore = -1;
      for (const [pid, score] of Object.entries(G.scores)) {
        if (score > highScore) {
          highScore = score;
          winner = pid;
        }
      }
      return { winner };
    }
  },
};
`,
  },

  // ─── patches/capnp-ts@0.7.0.patch ─────────────────────────────
  {
    path: "patches/capnp-ts@0.7.0.patch",
    content: `diff --git a/src/serialization/arena/single-segment-arena.js b/src/serialization/arena/single-segment-arena.js
index 3edc8b54e08d5ec01715648580c1b57db4b4f64e..eda0fff6207450e823b888556da3c5acdde61615 100644
--- a/src/serialization/arena/single-segment-arena.js
+++ b/src/serialization/arena/single-segment-arena.js
@@ -39,7 +39,8 @@ function allocate(minSize, segments, s) {
     else {
         minSize = util_1.padToWord(minSize);
     }
-    s.buffer = new ArrayBuffer(srcBuffer.byteLength + minSize);
+    const newSize = Math.max(srcBuffer.byteLength + minSize, srcBuffer.byteLength * 2);
+    s.buffer = new ArrayBuffer(newSize);
     // PERF: Assume that the source and destination buffers are word-aligned and use Float64Array to copy them one word
     // at a time.
     new Float64Array(s.buffer).set(new Float64Array(srcBuffer));
`,
  },

  // ─── .gitignore ──────────────────────────────────────────────
  {
    path: ".gitignore",
    content: `node_modules/
dist/
.partykit/
*.log
.DS_Store
`,
  },
];

/**
 * Get all template files with variable substitution applied.
 */
export function getTemplates(_vars: TemplateVars): TemplateFile[] {
  return rawTemplates.map(({ path, content }) => ({
    path,
    content: (v: TemplateVars) => substitute(content, v),
  }));
}
